apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitsync-emojivoto
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test
              image: alpine
              command:
                - ash
                - -c
                - /scripts/sync.sh
              volumeMounts:
                # a mount for site-data
                - name: ssh
                  mountPath: /root/.ssh/id_ed25519
                  subPath: id_ed25519
                # another mount for nginx config
                - name: ssh
                  mountPath: /root/.ssh/id_ed25519.pub
                  subPath: id_ed25519.pub
                - name: scripts
                  mountPath: /scripts
          volumes:
            - name: ssh
              secret:
                secretName: gitsync-ssh
                items:
                  - key: gitsync
                    path: id_ed25519
                    mode: 0600
                  - key: gitsync.pub
                    path: id_ed25519.pub
                    mode: 0600
            - name: scripts
              configMap:
                name: syncscript
                items:
                  - key: sync.sh
                    path: sync.sh
                    mode: 0777
          restartPolicy: OnFailure
