apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: softserve
  labels:
    app: softserve
spec:
  ports:
    - port: 22
      name: git-ssh
  clusterIP: None
  selector:
    app: softserve
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: softserve
  namespace: softserve
spec:
  selector:
    matchLabels:
      app: softserve
  serviceName: git
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: softserve
    spec:
      containers:
        - name: softserve
          image: charmcli/soft-serve:v0.2.2
          env:
            - name: SOFT_SERVE_HOST
              value: softserve-1.git.softserve.svc.cluster.local
            - name: SOFT_SERVE_PORT
              value: "22"
          ports:
            - containerPort: 22
              name: git-ssh
          volumeMounts:
            - name: softserve
              mountPath: /soft-serve
  volumeClaimTemplates:
    - metadata:
        name: softserve
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "civo-volume"
        resources:
          requests:
            storage: 5Gi
